//! Tool definitions and executor trait for the Claude API.

use async_trait::async_trait;
use serde::Serialize;
use serde_json::Value;
use std::path::PathBuf;

/// Result of executing a tool.
#[derive(Clone, Debug, Default)]
pub struct ToolResult {
    /// Text result to return to Claude.
    pub text: String,
    /// Optional file attachments generated by the tool.
    pub attachments: Vec<PathBuf>,
}

impl ToolResult {
    /// Create a new tool result with just text.
    pub fn new(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            attachments: Vec::new(),
        }
    }

    /// Create a tool result with text and an attachment.
    pub fn with_attachment(text: impl Into<String>, path: impl Into<PathBuf>) -> Self {
        Self {
            text: text.into(),
            attachments: vec![path.into()],
        }
    }
}

impl From<String> for ToolResult {
    fn from(text: String) -> Self {
        Self::new(text)
    }
}

impl From<&str> for ToolResult {
    fn from(text: &str) -> Self {
        Self::new(text)
    }
}

/// Trait for executing tools. Implement this to provide tool capabilities.
#[async_trait]
pub trait ToolExecutor: Send + Sync {
    /// Get the list of available tools as JSON tool definitions.
    fn tools(&self) -> Vec<Tool>;

    /// Check if this executor handles a tool with the given name.
    fn has_tool(&self, name: &str) -> bool {
        self.tools().iter().any(|t| t.name == name)
    }

    /// Execute a tool by name with the given input arguments.
    /// Returns the result to be sent back to Claude, potentially with attachments.
    async fn execute(&self, name: &str, input: &Value) -> Result<ToolResult, String>;
}

/// A tool definition for the Claude API.
#[derive(Clone, Debug, Serialize)]
pub struct Tool {
    /// The name of the tool.
    pub name: &'static str,
    /// A description of what the tool does.
    pub description: &'static str,
    /// JSON schema for the tool's input parameters.
    pub input_schema: Value,
}
